### PR TITLE
v3.7.5

### PR DESCRIPTION
**Pull request by superboyiii**
v3.7.5 hotfix

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Does we want to change master in this repo?

**Comment by superboyiii** [comment]
> Does we want to change master in this repo?

Seems nothing incompatible in master, it's good to release on master.

**Review by AnnaShaleva — APPROVED** [review]

**Comment by AnnaShaleva** [comment]
> Does we want to change master in this repo?

It's good to have these fixes in master.

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
> > Does we want to change master in this repo?
> 
> It's good to have these fixes in master.

Agree

**Review by shargon — COMMENTED** [review]
LGTM

**Pull request merged**
