### PR TITLE
Log plugin

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo/pull/980/files

### CODE REVIEW

**Comment by erikzhang** [comment]
No. We should create a new plugin. "ApplicationLog` is for logging transaction execution results.

**Comment by shargon** [comment]
Maybe we should rename `ApplicationLog`, the expected behaviour is for logs 😆

**Comment by igormcoelho** [comment]
Let's create a new plugin, `SystemLog` plugin, and use for this. ApplicationLog is less logging and more application data processing itself.

**Comment by shargon** [comment]
if we decide the name, i can make the changes

**Pull request closed without merging**
