### PR TITLE
Fix ApplicationLog

### LINKED ISSUE #152: Applicationlog param verification fail
Applied the latest Applicationlog Plugin on master branch.
Applicationlog Plugin responsed "Invalid params" when invoke a normal tx(I tried genesis tx and one ordinary tx).
image
It breaks here:
image
In getBlock, it returns this tx normally.
image

### PR DESCRIPTION
**Pull request by erikzhang**
Fixes #152

### CODE REVIEW

**Comment by shargon** [comment]
This will require https://github.com/neo-project/neo/pull/1315 ?

**Comment by erikzhang** [comment]
No.

**Comment by superboyiii** [comment]
Tested, eventlogs appear. However, issue still exists on Base64 encoding.
image
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "txid": "0x2b03f7a8db3649c9e2cb6d429dd358819b3fd536825d2a698e19de237583e60a",
        "trigger": "Application",
        "vmstate": "HALT",
        "gas_consumed": "0",
        "stack": [],
        "notifications": [
            {
                "contract": "0x43cf98eddbe047e198a3e5d57006311442a0ca15",
                "state": {
                    "type": "Array",
                    "value": [
                        {
                            "type": "ByteArray",
                            "value": "VHJhbnNmZXI="
                        },
                        {
                            "type": "Any"
                        },
                        {
                            "type": "ByteArray",
                            "value": "0wzwBoLXDacAgxEkGaxxo1Ezxh4="
                        },
                        {
                            "type": "Integer",
                            "value": "100000000"
                        }
                    ]
                }
            },
            {
                "contract": "0xa1760976db5fcdfab2a9930e8f6ce875b2d18225",
                "state": {
                    "type": "Array",
                    "value": [
                        {
                            "type": "ByteArray",
                            "value": "VHJhbnNmZXI="
                        },
                        {
                            "type": "Any"
                        },
                        {
                            "type": "ByteArray",
                            "value": "0wzwBoLXDacAgxEkGaxxo1Ezxh4="
                        },
                        {
                            "type": "Integer",
                            "value": "3000000000000000"
                        }
                    ]
                }
            }
        ]
    }
}
```
You see, "VHJhbnNmZXI="  base64 decoding => "Transfer", it's correct.
But what's "0wzwBoLXDacAgxEkGaxxo1Ezxh4="? It can't be base64 decoding.
@erikzhang

**Comment by erikzhang** [comment]
```json
{
  "type": "ByteArray",
  "value": "0wzwBoLXDacAgxEkGaxxo1Ezxh4="
}
```

This is a `ByteArray`. So you can decode it to a `byte[]`. In this case, then you convert it to an `UInt160` or address.

**Comment by superboyiii** [comment]
> ```json
> {
>   "type": "ByteArray",
>   "value": "0wzwBoLXDacAgxEkGaxxo1Ezxh4="
> }
> ```
> 
> This is a `ByteArray`. So you can decode it to a `byte[]`.
> 
> In this case (I mean `Transfer`), then you convert it to an `UInt160` or address.

I know what you said, but the issue is that this ```toAddress```: ```0wzwBoLXDacAgxEkGaxxo1Ezxh4``` is not illegal for Base64 decoding! So can you try it? "0wzwBoLXDacAgxEkGaxxo1Ezxh4=" base64 decoding? From myside, it's not able to be done.
image

**Comment by erikzhang** [comment]
This is a **byte array**, not a string.

**Pull request merged**
