### PR TITLE
Prevent DoS with wrong files

### PR DESCRIPTION
**Pull request by shargon**
According to this line, we can't have any block more than this constant, so i think that is a good practice to avoid any buffer bigger than this value
https://github.com/neo-project/neo/blob/3a06f9c0efcc3cc267d380bb945fe7474b1f2243/neo/Network/P2P/Message.cs#L12

### CODE REVIEW

**Comment by igormcoelho** [comment]
Fully agreed Shargon!
Do you think it's better to launch an exception in case it's bigger? otherwise, how will we know the exact cause? Bypassing this "error" with a simple break (ignoring block) seems strange to me.

**Comment by shargon** [comment]
If we throw an exception in this point, will be captured and showed?

**Comment by vncoelho** [comment]
I think so, @shargon, maybe it is better to launch an exception, stop and notify.

**Comment by shargon** [comment]
@vncoelho could you tested if the exception is successfully captured?

**Comment by vncoelho** [comment]
Sure, my friend. I will need a couple of days. Until next Tuesday perhaps, can be? It is holiday here. :dancer:

**Comment by vncoelho** [comment]
@shargon, I think that maybe we will wait for https://github.com/neo-project/neo-cli/pull/357.

Do you want to merge this for master-2.x as well?

**Comment by shargon** [comment]
For both

**Comment by shargon** [comment]
https://github.com/neo-project/neo-cli/pull/357 is done @vncoelho

**Comment by vncoelho** [comment]
@shargon, I think that we should have neocli 3x running before merging this. Lets remember to test it when the time comes.

**Pull request merged**
