### PR TITLE
Fix RpcSystemAssetTracker

### PR DESCRIPTION
**Pull request by superboyiii**
Fix RpcSystemAssetTracker for multi nodes running on one PC.

### CODE REVIEW

**Comment by superboyiii** [comment]
Tested.
image

**Comment by vncoelho** [comment]
Hi @superboyiii, I think I did not see this before because usually we run on indivual containers when settling privatenets.

I did not understand the problem very well...aehuahea
But I believe that your fix are always good!
If you could guide me the procedure for having this problem I can try to reproduce and test.

**Comment by superboyiii** [comment]
> Hi @superboyiii, I think I did not see this before because usually we run on indivual containers when settling privatenets.
> 
> I did not understand the problem very well...aehuahea
> But I believe that your fix are always good!
> If you could guide me the procedure for having this problem I can try to reproduce and test.

Hi @vncoelho  In the before case, if we installed RpcSystemAssetTracker plugin in two nodes and start them together, there'll be a conflict between these nodes since they're using the same relative dbPath. The second node wasn't able to start. If turn it to full Path, there'll never be any conflict. This situation can always be seen on running multi nodes on one PC.

**Comment by vncoelho** [comment]
@superboyiii with superpower's...good to see you merging this! 
As I said, since we were always running with docker we did not see this problem. It is good that you found.

**Comment by superboyiii** [comment]
@vncoelho Ahaahaaha.....Thanks.

**Pull request merged**
