### PR TITLE
Add fee information in ApplicationLogs plugin

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-plugins/issues/137

### CODE REVIEW

**Comment by shargon** [comment]
@hal0x2328 please review it if this can solve the problem

**Comment by hal0x2328** [comment]
It's a good thing to have the fees split out separately in the log but I don't think it solves the problem if the notification from the GAS contract still shows address B receiving the entire balance from address A - how do you know in which case to subtract the fee from that total, since it only happens when the amount transferred is A's entire balance?

Although you could make the plugin subtract the fee from the notification, it seems like it should probably be fixed in the GAS contract itself.

**Comment by shargon** [comment]
it's for neo2 or neo3?

**Comment by hal0x2328** [comment]
> it's for neo2 or neo3?

Neo3

**Comment by shargon** [comment]
I will transfer the issue to the neo repository

**Pull request closed without merging**
