### PR TITLE
Commit as the final step of persistence in StatesDumper

### PR DESCRIPTION
**Pull request by jsolman**
Use the new `Commit` method for performing writes. See neo-project/neo#568

### CODE REVIEW

**Comment by jsolman** [comment]
It probably goes without saying, but the next Neo release must be made and referenced in the csproj before this can be merged.

**Comment by jsolman** [comment]
@vncoelho You should have waited to merge this probably until it is referencing the next release of Neo. This isn't compatible with version 2.9.4

**Comment by vncoelho** [comment]
Your commit on Neo core already destroyed the plugin, it was needed for fixing StateDumper.

**Comment by jsolman** [comment]
This project doesn't reference the commit though, it references the 2.9.4 release.

**Comment by vncoelho** [comment]
Anhhhh, you are right.
In this sense, yes, since I do not use visual studio I missed that. We use a script that get all the masters and keep it compiling.
I personally think it is good, because it keeps like a Travis CI on (neo-cli,neo-vm,neo-plugins and neo).

**Comment by erikzhang** [comment]
You can use VS Code. https://code.visualstudio.com

**Pull request merged**
