### PR TITLE
Aggregate - Plugin Improvements for Neo 2.10.1

### PR DESCRIPTION
**Pull request by jsolman**
This rolls up the following changes:
* Fix application logs after adding EventStream usage and OnPluginsLoaded. (#55)
* Import blocks after plugins are loaded. (#53)
* Add Plugin for UTXO tracking by account. (#52)

### CODE REVIEW

**Comment by erikzhang** [comment]
I prefer that each PR submit a separate feature instead of a bunch of changes mixed together.

**Comment by jsolman** [comment]
I can break them back apart, but there are individual PRs for each in this aggregate.

**Comment by jsolman** [comment]
In this case people that want to use 2.10.1 plugins really want to have one branch to get them all, but I don’t necessarily have to make a single PR for it, so I can break it back out into multiple PRs against master if you want.

**Comment by erikzhang** [comment]
Yes, please break it back out into multiple PRs against master.

**Comment by vncoelho** [comment]
It is also my fault, @erikzhang, I was also supporting this for an easy way to test all together. I believe that after revised it becomes easier, but this case was outstanding because we needed to change 3 plugins.

If you prefer everything split let's split it back.

**Comment by jsolman** [comment]
I will split it back into multiple PRs against master. I do kind of think there should be a branch for 2.10.0 and 2.10.1 though, because for example the 2.10.0 and 2.10.1 important blocks plugin need to be different. I’ll have a pr out against master for both, we can merge the 2.10.0 one first since it works with the current neo-cli release, but devs and some others may need the code that works against 2.10.1.

**Comment by jsolman** [comment]
Changes for ApplicationLogs plugin, Import Blocks Plugin, and UTXO tracking plugin have been split out independently.

**Pull request closed without merging**
