### PR TITLE
Fix missing public declaration on pre/post process functions

### PR DESCRIPTION
**Pull request by vncoelho**

### CODE REVIEW

**Comment by erikzhang** [comment]
Not good. 😕

**Comment by erikzhang** [comment]
@shargon You need to test before approving.
@vncoelho You need to test before merging.

**Comment by jsolman** [comment]
FYI: The csproj file still references 2.9.4 where the interface for RpcPlugin doesn’t even contain these methods.

**Comment by erikzhang** [comment]
> The csproj file still references 2.9.4 where the interface for RpcPlugin doesn’t even contain these methods.

Yes. So why do we create one pr for adding `PreProcess()` and `PostProcess()`, one pr for adding `public`, and another pr for adding reference to 2.10.0?

**Comment by jsolman** [comment]
Vitor was in a hurry for some reason. You will have to have him answe it. @vncoelho

**Comment by shargon** [comment]
Maybe should be better with `protect` ?

**Comment by vncoelho** [comment]
The masters should build and that inclusion in NEO core had broken 2 plugins.

The public was a minor problem, it should had come with the function.

**Comment by vncoelho** [comment]
The public was copied from the RPC wallet but it probably could be protected.

**Pull request merged**
