### PR TITLE
v2.9.3

### LINKED ISSUE #29: Fix plugins with Hot configuration
We need to fix all plugins with `Overide Configure` and `GetConfiguration` in order to make it compile with Neo master.

### PR DESCRIPTION
**Pull request by erikzhang**
Closes #29

### CODE REVIEW

**Comment by vncoelho** [comment]
Thanks for this update, @erikzhang.

**Comment by erikzhang** [comment]
It can't be merged now because it refers to the daily build version of Neo.

**Comment by shargon** [comment]
We can merge and release new versions?

**Comment by erikzhang** [comment]
> Can we merge and release new versions?

We need to wait for https://github.com/neo-project/neo-plugins/pull/34

**Pull request merged**
