### PR TITLE
Add RpcWallet

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by jsolman** [comment]
Should all the code that deals with maintaining wallet db indices be moved into the plugin also? Did you plan to do this still?

**Comment by jsolman** [comment]
Actually I guess it is more work if an attempt were made to move wallet tracking into the plugin since the cli will still interact with the wallet directly. It would need other interfaces for the cli to interact with the plugin. Still it is perhaps something to consider for the future.

**Comment by shargon** [comment]
Good move :)

**Comment by erikzhang** [comment]
Waiting for the test from NGD.

**Pull request merged**
